use std::path::PathBuf;

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use rclone_remotes::config::File;
use rclone_remotes::ctl::{self, Request};
use rclone_remotes::{mounts, pair};

#[derive(Parser)]
#[command(version, about)]
struct Cli {
    /// JSON configuration generated by the NixOS module.
    #[arg(long, short, env = "RCLONE_REMOTES_CONFIG", global = true)]
    config: Option<PathBuf>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Check that the configuration parses and is coherent, then exit.
    Validate,
    /// Copy credential-backed mount configs to their writable staging paths.
    StageMountConfigs,
    /// Detach stale rclone FUSE mounts after resume and reset their units.
    MountReset,
    /// Run one bisync pair: the service behind `rclone-bisync-<name>.service`.
    Run,
    /// Talk to a running pair.
    Ctl {
        /// Pair name; selects /run/rclone-remotes/<name>/ctl.sock.
        #[arg(long, short, required_unless_present = "socket")]
        name: Option<String>,
        /// Control socket, overriding --name.
        #[arg(long)]
        socket: Option<PathBuf>,
        #[command(subcommand)]
        action: CtlAction,
    },
}

#[derive(Subcommand, Clone, Copy)]
enum CtlAction {
    /// Print the pair's state as JSON.
    Status,
    /// Pull now; returns when the pass has finished.
    Sync,
    /// Rebuild the listings from scratch (`--resync`).
    Resync,
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_ansi(false)
        .without_time()
        .with_target(false)
        .init();

    let cli = Cli::parse();
    let config = || -> Result<File> {
        let path = cli
            .config
            .as_ref()
            .context("--config (or RCLONE_REMOTES_CONFIG) is required")?;
        File::load(path)
    };

    match &cli.command {
        Command::Validate => config().map(|_| ()),
        Command::StageMountConfigs => mounts::stage_configs(&config()?.into_global()?),
        Command::MountReset => mounts::reset_mounts(&config()?.into_global()?),
        Command::Run => {
            let cfg = config()?.into_pair()?;
            let rt = pair::Runtime::from_env()?;
            tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()?
                .block_on(pair::run(cfg, rt))
        }
        Command::Ctl {
            name,
            socket,
            action,
        } => {
            let socket = match (socket, name) {
                (Some(s), _) => s.clone(),
                (None, Some(n)) => ctl::default_socket(n),
                (None, None) => bail!("--name or --socket is required"),
            };
            let req = match action {
                CtlAction::Status => Request::Status,
                CtlAction::Sync => Request::Sync,
                CtlAction::Resync => Request::Resync,
            };
            let resp = ctl::call(&socket, req)?;
            println!("{}", serde_json::to_string_pretty(&resp.status)?);
            if !resp.ok {
                bail!(resp.message.unwrap_or_else(|| "failed".into()));
            }
            Ok(())
        }
    }
}
